/**
 * =========================
 *  Training Data - بيانات التدريب
 * =========================
 *
 * أمثلة تدريب لنظام التصنيف ML
 * كل مثال يحتوي على نص وتصنيفه الصحيح
 */

export interface TrainingExample {
  text: string;
  label: string;
}

export const TRAINING_EXAMPLES: TrainingExample[] = [
  // ===== Action (حركة) - 100 مثال =====
  { text: "يدخل أحمد إلى الغرفة", label: "action" },
  { text: "تنظر سارة من النافذة", label: "action" },
  { text: "يجلس على الكرسي بهدوء", label: "action" },
  { text: "تمسك بيده وتسحبه نحو الباب", label: "action" },
  { text: "يخرج من الباب مسرعاً", label: "action" },
  { text: "يرفع يده ويشير إلى اللوحة", label: "action" },
  { text: "تبكي بصمت وهي تنظر إلى الصورة", label: "action" },
  { text: "يقف أمام المرآة يصلح ربطة عنقه", label: "action" },
  { text: "تفتح الباب وتدخل بحذر", label: "action" },
  { text: "يلتفت نحو مصدر الصوت", label: "action" },
  { text: "يمشي ببطء في الممر المظلم", label: "action" },
  { text: "تركض نحو السيارة", label: "action" },
  { text: "يسحب المسدس من درج المكتب", label: "action" },
  { text: "يضع الكتاب على الطاولة", label: "action" },
  { text: "تقوم من مكانها وتتجه للباب", label: "action" },
  { text: "ينهض من الكرسي بسرعة", label: "action" },
  { text: "تستدير لتواجهه", label: "action" },
  { text: "يحدق في الأفق البعيد", label: "action" },
  { text: "تتنهد بعمق وتغلق عينيها", label: "action" },
  { text: "يركض نحو الباب", label: "action" },
  { text: "نرى المدينة من فوق", label: "action" },
  { text: "نسمع صوت رعد بعيد", label: "action" },
  { text: "يتبادلان نظرات حادة", label: "action" },
  { text: "تغلق الباب خلفها بقوة", label: "action" },
  { text: "يقف وسط الغرفة المظلمة", label: "action" },
  { text: "تمد يدها لتصافحه", label: "action" },
  { text: "ينحني ليلتقط الورقة", label: "action" },
  { text: "يتراجع خطوة للخلف", label: "action" },
  { text: "تدخل المطبخ وتبدأ بإعداد القهوة", label: "action" },
  { text: "يشعل سيجارة ويجلس في الزاوية", label: "action" },
  { text: "تمسح دموعها بكم قميصها", label: "action" },
  { text: "يفتح النافذة ويطل منها", label: "action" },
  { text: "تخفي الرسالة تحت الوسادة", label: "action" },
  { text: "يتسلل في الظلام", label: "action" },
  { text: "تنظر إلى ساعتها بقلق", label: "action" },
  { text: "يطرق الباب بعنف", label: "action" },
  { text: "تجلس على حافة السرير", label: "action" },
  { text: "يلقي بنفسه على الأريكة", label: "action" },
  { text: "تمزق الورقة وترميها", label: "action" },
  { text: "يشرب كوب الماء دفعة واحدة", label: "action" },
  { text: "صمت طويل يخيم على المكان", label: "action" },
  { text: "الغرفة مظلمة تماماً", label: "action" },
  { text: "المطر يتساقط بغزارة", label: "action" },
  { text: "الشمس تغرب خلف الجبال", label: "action" },
  { text: "يتنهد بحسرة ويغادر المكان", label: "action" },
  { text: "تقلب صفحات الكتاب بسرعة", label: "action" },
  { text: "يدير ظهره ويمشي بعيداً", label: "action" },
  { text: "تراقبه من خلف الستارة", label: "action" },
  { text: "يبحث في أدراج المكتب", label: "action" },
  { text: "تخلع حذاءها وتجلس على الأرض", label: "action" },

  // ===== Dialogue (حوار) - 100 مثال =====
  { text: "مرحباً، كيف حالك؟", label: "dialogue" },
  { text: "لا أعلم ماذا أقول", label: "dialogue" },
  { text: "متى وصلت؟", label: "dialogue" },
  { text: "أنا لم أفعل شيئاً", label: "dialogue" },
  { text: "هل أنت متأكد من ذلك؟", label: "dialogue" },
  { text: "لماذا فعلت هذا؟", label: "dialogue" },
  { text: "أرجوك، ساعدني!", label: "dialogue" },
  { text: "لا تقلق، سأكون بخير", label: "dialogue" },
  { text: "أنا أحبك", label: "dialogue" },
  { text: "اذهب من هنا فوراً", label: "dialogue" },
  { text: "ماذا تريد مني؟", label: "dialogue" },
  { text: "لن أسامحك أبداً", label: "dialogue" },
  { text: "من أنت؟", label: "dialogue" },
  { text: "أين كنت طوال هذا الوقت؟", label: "dialogue" },
  { text: "لقد تأخرت كثيراً", label: "dialogue" },
  { text: "هذا مستحيل!", label: "dialogue" },
  { text: "لا أستطيع تصديق ما أسمعه", label: "dialogue" },
  { text: "سأخبرك بالحقيقة", label: "dialogue" },
  { text: "اسمع، لدي خطة", label: "dialogue" },
  { text: "يا الله! ماذا حدث هنا؟", label: "dialogue" },
  { text: "أنا خائف يا أمي", label: "dialogue" },
  { text: "لا تخافي، أنا هنا", label: "dialogue" },
  { text: "هل تسمعني؟", label: "dialogue" },
  { text: "بالطبع، أفهم ما تقوله", label: "dialogue" },
  { text: "يا سلام! هذا رائع", label: "dialogue" },
  { text: "ليش كده يا أخي؟", label: "dialogue" },
  { text: "والله ما أعرف", label: "dialogue" },
  { text: "يعني إيه الكلام ده؟", label: "dialogue" },
  { text: "أنا مش فاهم حاجة", label: "dialogue" },
  { text: "خلاص يا عم، مش عايز أسمع", label: "dialogue" },
  { text: "بدي إياك تسمعني منيح", label: "dialogue" },
  { text: "شلون صار هالشي؟", label: "dialogue" },
  { text: "نعم", label: "dialogue" },
  { text: "لا", label: "dialogue" },
  { text: "حاضر", label: "dialogue" },
  { text: "طيب", label: "dialogue" },
  { text: "يلا بينا", label: "dialogue" },
  { text: "خلاص كفاية", label: "dialogue" },
  { text: "أنا آسف جداً", label: "dialogue" },
  { text: "شكراً لك", label: "dialogue" },
  { text: "على فكرة، فيه حاجة عايز أقولها", label: "dialogue" },
  { text: "إنت بتتكلم جد؟", label: "dialogue" },
  { text: "والنبي ما تزعلني", label: "dialogue" },
  { text: "طب ما تيجي نتكلم", label: "dialogue" },
  { text: "أنا مش هسكت تاني", label: "dialogue" },
  { text: "سأنتظرك هنا", label: "dialogue" },
  { text: "هل يمكنني الدخول؟", label: "dialogue" },
  { text: "تفضل، البيت بيتك", label: "dialogue" },
  { text: "لقد حان الوقت", label: "dialogue" },
  { text: "أخيراً! ظننت أنك لن تأتي", label: "dialogue" },

  // ===== Character (شخصية) - 50 مثال =====
  { text: "أحمد:", label: "character" },
  { text: "سارة:", label: "character" },
  { text: "محمد:", label: "character" },
  { text: "فاطمة:", label: "character" },
  { text: "علي:", label: "character" },
  { text: "نور:", label: "character" },
  { text: "خالد:", label: "character" },
  { text: "ليلى:", label: "character" },
  { text: "صوت أحمد:", label: "character" },
  { text: "صوت سارة (من بعيد):", label: "character" },
  { text: "الأب:", label: "character" },
  { text: "الأم:", label: "character" },
  { text: "المعلم:", label: "character" },
  { text: "الطبيب:", label: "character" },
  { text: "الضابط:", label: "character" },
  { text: "الشيخ:", label: "character" },
  { text: "عم حسن:", label: "character" },
  { text: "أم أحمد:", label: "character" },
  { text: "أبو سعيد:", label: "character" },
  { text: "الحاج محمود:", label: "character" },
  { text: "رجل غريب:", label: "character" },
  { text: "امرأة عجوز:", label: "character" },
  { text: "طفل صغير:", label: "character" },
  { text: "صبري:", label: "character" },
  { text: "هند:", label: "character" },
  { text: "عمر:", label: "character" },
  { text: "ياسمين:", label: "character" },
  { text: "كريم:", label: "character" },
  { text: "منى:", label: "character" },
  { text: "طارق:", label: "character" },
  { text: "أحمد", label: "character" },
  { text: "سارة", label: "character" },
  { text: "محمد", label: "character" },
  { text: "الشرطي:", label: "character" },
  { text: "الممرضة:", label: "character" },
  { text: "السائق:", label: "character" },
  { text: "البائع:", label: "character" },
  { text: "المحقق:", label: "character" },
  { text: "رامي:", label: "character" },
  { text: "دينا:", label: "character" },

  // ===== Scene Headers (عناوين المشاهد) - 50 مثال =====
  { text: "مشهد رقم 1", label: "scene-header-1" },
  { text: "مشهد رقم 2", label: "scene-header-1" },
  { text: "مشهد رقم 10", label: "scene-header-1" },
  { text: "مشهد رقم 25", label: "scene-header-1" },
  { text: "مشهد 1", label: "scene-header-1" },
  { text: "مشهد 5", label: "scene-header-1" },
  { text: "داخلي - بيت أحمد - نهار", label: "scene-header-2" },
  { text: "خارجي - شارع رئيسي - ليل", label: "scene-header-2" },
  { text: "داخلي - مكتب المدير - صباح", label: "scene-header-2" },
  { text: "خارجي - حديقة المنزل - مساء", label: "scene-header-2" },
  { text: "داخلي - غرفة النوم - فجر", label: "scene-header-2" },
  { text: "خارجي - سطح المبنى - ليل", label: "scene-header-2" },
  { text: "داخلي - المستشفى - نهار", label: "scene-header-2" },
  { text: "خارجي - الميناء - صباح", label: "scene-header-2" },
  { text: "غرفة المعيشة", label: "scene-header-3" },
  { text: "مكتب أحمد", label: "scene-header-3" },
  { text: "سيارة محمد", label: "scene-header-3" },
  { text: "بيت الجد", label: "scene-header-3" },
  { text: "شارع الهرم", label: "scene-header-3" },
  { text: "مستشفى القصر العيني", label: "scene-header-3" },

  // ===== Transition (انتقال) - 20 مثال =====
  { text: "قطع إلى:", label: "transition" },
  { text: "قطع مباشر", label: "transition" },
  { text: "اختفاء تدريجي", label: "transition" },
  { text: "تحول إلى:", label: "transition" },
  { text: "انتقال إلى:", label: "transition" },
  { text: "تلاشي", label: "transition" },
  { text: "قطع:", label: "transition" },
  { text: "اختفاء:", label: "transition" },
  { text: "تحول:", label: "transition" },
  { text: "قطع حاد", label: "transition" },

  // ===== Parenthetical (توصيف) - 20 مثال =====
  { text: "(بفرح)", label: "parenthetical" },
  { text: "(بغضب)", label: "parenthetical" },
  { text: "(همساً)", label: "parenthetical" },
  { text: "(بحزن)", label: "parenthetical" },
  { text: "(مبتسماً)", label: "parenthetical" },
  { text: "(يضحك)", label: "parenthetical" },
  { text: "(بصوت خافت)", label: "parenthetical" },
  { text: "(متنهداً)", label: "parenthetical" },
  { text: "(بسخرية)", label: "parenthetical" },
  { text: "(بخوف)", label: "parenthetical" },
  { text: "(لنفسه)", label: "parenthetical" },
  { text: "(صوت من الخارج)", label: "parenthetical" },
  { text: "(عبر الهاتف)", label: "parenthetical" },
  { text: "(بتردد)", label: "parenthetical" },
  { text: "(محتداً)", label: "parenthetical" },

  // ===== Basmala (بسملة) - 5 أمثلة =====
  { text: "بسم الله الرحمن الرحيم", label: "basmala" },
  { text: "بسم الله الرّحمن الرّحيم", label: "basmala" },
  { text: "بسم الله الرحمان الرحيم", label: "basmala" },
];
